"""initial schema

Revision ID: a36a2c0cab7f
Revises: 
Create Date: 2026-03-16 17:13:25.692559

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a36a2c0cab7f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('machinery', sa.String(length=20), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'available'"), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('snapshot', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machines')),
    sa.UniqueConstraint('name', name=op.f('uq_machines_name'))
    )
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('file_hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('file_hash_md5', sa.String(length=32), nullable=True),
    sa.Column('file_hash_sha1', sa.String(length=40), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_type', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('verdict', sa.String(length=20), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('score', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions'))
    )
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('report_es_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_analyses_machine_id_machines')),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_analyses_submission_id_submissions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analyses')
    op.drop_table('submissions')
    op.drop_table('machines')
    # ### end Alembic commands ###
