/*
 * crypt_stub.c — training sample for Module 4.2 (custom packers / unpacking
 * stubs). BENIGN. It models the essence of a packer: an encrypted payload blob
 * (`enc[]`) plus a tiny "stub" (`unpack()`) that decrypts it into a buffer at
 * runtime and then uses it. There is no readable payload string in the binary —
 * you must recover the key and decrypt, exactly as with a real packed sample.
 *
 * The "OEP moment" here is the point right after the decrypt loop where the
 * plaintext exists in memory. That's where, with a real packer, you'd dump.
 *
 * Build:  gcc -O0 -fno-stack-protector -no-pie crypt_stub.c -o crypt_stub
 * Run:    ./crypt_stub            # prints the decrypted payload
 *
 * Generated by: python3 xorpack.py encode "FLAG{unpacked_at_runtime}" K3yz
 */
#include <stdio.h>
#include <string.h>

static const char KEY[] = "K3yz";   /* the repeating XOR key */

/* enc[] = XOR("FLAG{unpacked_at_runtime}", "K3yz") */
static unsigned char enc[] = {
    0x0d, 0x7f, 0x38, 0x3d, 0x30, 0x46, 0x17, 0x0a, 0x2a, 0x50,
    0x12, 0x1f, 0x2f, 0x6c, 0x18, 0x0e, 0x14, 0x41, 0x0c, 0x14,
    0x3f, 0x5a, 0x14, 0x1f, 0x36
};

/* The "unpacking stub": decrypt enc[] in place into out[]. */
static void unpack(char *out, size_t n) {
    size_t klen = strlen(KEY);
    for (size_t i = 0; i < n; i++)
        out[i] = (char)(enc[i] ^ KEY[i % klen]);   /* <-- the decrypt loop */
    out[n] = '\0';
    /* <-- "OEP": plaintext now lives in out[]; a dumper would grab it here. */
}

int main(void) {
    char out[64];
    unpack(out, sizeof(enc));
    printf("payload: %s\n", out);
    return 0;
}
